INSERT INTO skills (skill_name, department_id)
SELECT 'Genomics', d.id FROM departments d WHERE d.name = 'Computational Biology'
UNION ALL SELECT 'Transcriptomics', d.id FROM departments d WHERE d.name = 'Computational Biology'
UNION ALL SELECT 'Proteomics', d.id FROM departments d WHERE d.name = 'Computational Biology'
UNION ALL SELECT 'Single-cell RNA-seq (scRNA-seq)', d.id FROM departments d WHERE d.name = 'Computational Biology'
UNION ALL SELECT 'Multi-omics Integration', d.id FROM departments d WHERE d.name = 'Computational Biology'
UNION ALL SELECT 'NGS Data Analysis', d.id FROM departments d WHERE d.name = 'Computational Biology'
UNION ALL SELECT 'Organoid Data Analysis', d.id FROM departments d WHERE d.name = 'Computational Biology'
UNION ALL SELECT 'Biomarker Discovery', d.id FROM departments d WHERE d.name = 'Computational Biology'
UNION ALL SELECT 'Target Identification', d.id FROM departments d WHERE d.name = 'Computational Biology'
UNION ALL SELECT 'Pathway Analysis', d.id FROM departments d WHERE d.name = 'Computational Biology'
UNION ALL SELECT 'Systems Biology', d.id FROM departments d WHERE d.name = 'Computational Biology'
UNION ALL SELECT 'Biological Knowledge Graphs', d.id FROM departments d WHERE d.name = 'Computational Biology'

UNION ALL SELECT 'Molecular Docking', d.id FROM departments d WHERE d.name = 'Computational Chemistry'
UNION ALL SELECT 'Virtual Screening', d.id FROM departments d WHERE d.name = 'Computational Chemistry'
UNION ALL SELECT 'PROTAC Design', d.id FROM departments d WHERE d.name = 'Computational Chemistry'
UNION ALL SELECT 'Covalent Binder Design', d.id FROM departments d WHERE d.name = 'Computational Chemistry'
UNION ALL SELECT 'Small Molecule Design', d.id FROM departments d WHERE d.name = 'Computational Chemistry'
UNION ALL SELECT 'Reaction Modeling', d.id FROM departments d WHERE d.name = 'Computational Chemistry'
UNION ALL SELECT 'Catalysis Modeling', d.id FROM departments d WHERE d.name = 'Computational Chemistry'
UNION ALL SELECT 'Solid Form Prediction', d.id FROM departments d WHERE d.name = 'Computational Chemistry'
UNION ALL SELECT 'Crystal Structure Prediction', d.id FROM departments d WHERE d.name = 'Computational Chemistry'
UNION ALL SELECT 'Molecular Dynamics Simulation', d.id FROM departments d WHERE d.name = 'Computational Chemistry'
UNION ALL SELECT 'QSAR Modeling', d.id FROM departments d WHERE d.name = 'Computational Chemistry'
UNION ALL SELECT 'ADMET Prediction', d.id FROM departments d WHERE d.name = 'Computational Chemistry'

UNION ALL SELECT 'Drug Discovery', d.id FROM departments d WHERE d.name = 'Science'
UNION ALL SELECT 'Disease Biology', d.id FROM departments d WHERE d.name = 'Science'
UNION ALL SELECT 'Translational Research', d.id FROM departments d WHERE d.name = 'Science'
UNION ALL SELECT 'Scientific Writing', d.id FROM departments d WHERE d.name = 'Science'
UNION ALL SELECT 'Literature Mining', d.id FROM departments d WHERE d.name = 'Science'
UNION ALL SELECT 'Hypothesis Generation', d.id FROM departments d WHERE d.name = 'Science'
UNION ALL SELECT 'Experimental Design', d.id FROM departments d WHERE d.name = 'Science'
UNION ALL SELECT 'Data Interpretation', d.id FROM departments d WHERE d.name = 'Science'

UNION ALL SELECT 'Python', d.id FROM departments d WHERE d.name = 'Full Stack Data Scientist'
UNION ALL SELECT 'PyTorch', d.id FROM departments d WHERE d.name = 'Full Stack Data Scientist'
UNION ALL SELECT 'TensorFlow', d.id FROM departments d WHERE d.name = 'Full Stack Data Scientist'
UNION ALL SELECT 'Deep Learning', d.id FROM departments d WHERE d.name = 'Full Stack Data Scientist'
UNION ALL SELECT 'Generative AI', d.id FROM departments d WHERE d.name = 'Full Stack Data Scientist'
UNION ALL SELECT 'Large Language Models (LLMs)', d.id FROM departments d WHERE d.name = 'Full Stack Data Scientist'
UNION ALL SELECT 'Graph Neural Networks', d.id FROM departments d WHERE d.name = 'Full Stack Data Scientist'
UNION ALL SELECT 'Multi-modal Models', d.id FROM departments d WHERE d.name = 'Full Stack Data Scientist'
UNION ALL SELECT 'Feature Engineering', d.id FROM departments d WHERE d.name = 'Full Stack Data Scientist'
UNION ALL SELECT 'MLOps', d.id FROM departments d WHERE d.name = 'Full Stack Data Scientist'
UNION ALL SELECT 'Model Explainability', d.id FROM departments d WHERE d.name = 'Full Stack Data Scientist'
UNION ALL SELECT 'Bayesian Modeling', d.id FROM departments d WHERE d.name = 'Full Stack Data Scientist'

UNION ALL SELECT 'TypeScript', d.id FROM departments d WHERE d.name = 'Full Stack Developer'
UNION ALL SELECT 'React', d.id FROM departments d WHERE d.name = 'Full Stack Developer'
UNION ALL SELECT 'Next.js', d.id FROM departments d WHERE d.name = 'Full Stack Developer'
UNION ALL SELECT 'Node.js', d.id FROM departments d WHERE d.name = 'Full Stack Developer'
UNION ALL SELECT 'PostgreSQL', d.id FROM departments d WHERE d.name = 'Full Stack Developer'
UNION ALL SELECT 'REST APIs', d.id FROM departments d WHERE d.name = 'Full Stack Developer'
UNION ALL SELECT 'GraphQL', d.id FROM departments d WHERE d.name = 'Full Stack Developer'
UNION ALL SELECT 'Authentication & Authorization', d.id FROM departments d WHERE d.name = 'Full Stack Developer'
UNION ALL SELECT 'System Design', d.id FROM departments d WHERE d.name = 'Full Stack Developer'

UNION ALL SELECT 'HTML5', d.id FROM departments d WHERE d.name = 'Web Developer'
UNION ALL SELECT 'CSS3', d.id FROM departments d WHERE d.name = 'Web Developer'
UNION ALL SELECT 'TypeScript', d.id FROM departments d WHERE d.name = 'Web Developer'
UNION ALL SELECT 'React', d.id FROM departments d WHERE d.name = 'Web Developer'
UNION ALL SELECT 'Tailwind CSS', d.id FROM departments d WHERE d.name = 'Web Developer'
UNION ALL SELECT 'Responsive Design', d.id FROM departments d WHERE d.name = 'Web Developer'
UNION ALL SELECT 'Web Accessibility (WCAG)', d.id FROM departments d WHERE d.name = 'Web Developer'
UNION ALL SELECT 'Frontend Performance Optimization', d.id FROM departments d WHERE d.name = 'Web Developer'

UNION ALL SELECT 'Figma', d.id FROM departments d WHERE d.name = 'UI/UX Developer'
UNION ALL SELECT 'UX Research', d.id FROM departments d WHERE d.name = 'UI/UX Developer'
UNION ALL SELECT 'Design Systems', d.id FROM departments d WHERE d.name = 'UI/UX Developer'
UNION ALL SELECT 'Wireframing', d.id FROM departments d WHERE d.name = 'UI/UX Developer'
UNION ALL SELECT 'Prototyping', d.id FROM departments d WHERE d.name = 'UI/UX Developer'
UNION ALL SELECT 'Usability Testing', d.id FROM departments d WHERE d.name = 'UI/UX Developer'
UNION ALL SELECT 'Accessibility Design', d.id FROM departments d WHERE d.name = 'UI/UX Developer'
UNION ALL SELECT 'Interaction Design', d.id FROM departments d WHERE d.name = 'UI/UX Developer'

UNION ALL SELECT 'DevOps', d.id FROM departments d WHERE d.name = 'Engineering'
UNION ALL SELECT 'Docker', d.id FROM departments d WHERE d.name = 'Engineering'
UNION ALL SELECT 'Kubernetes', d.id FROM departments d WHERE d.name = 'Engineering'
UNION ALL SELECT 'CI/CD', d.id FROM departments d WHERE d.name = 'Engineering'
UNION ALL SELECT 'Cloud Infrastructure (AWS/GCP/Azure)', d.id FROM departments d WHERE d.name = 'Engineering'
UNION ALL SELECT 'Terraform', d.id FROM departments d WHERE d.name = 'Engineering'
UNION ALL SELECT 'Observability (Prometheus/Grafana)', d.id FROM departments d WHERE d.name = 'Engineering'
UNION ALL SELECT 'High Performance Computing (HPC)', d.id FROM departments d WHERE d.name = 'Engineering'

UNION ALL SELECT 'Software Architecture', d.id FROM departments d WHERE d.name = 'Developer'
UNION ALL SELECT 'API Design', d.id FROM departments d WHERE d.name = 'Developer'
UNION ALL SELECT 'Secure Coding', d.id FROM departments d WHERE d.name = 'Developer'
UNION ALL SELECT 'Distributed Systems', d.id FROM departments d WHERE d.name = 'Developer'
UNION ALL SELECT 'Code Review', d.id FROM departments d WHERE d.name = 'Developer'
UNION ALL SELECT 'Performance Optimization', d.id FROM departments d WHERE d.name = 'Developer'

UNION ALL SELECT 'Client Engagement', d.id FROM departments d WHERE d.name = 'Business Development'
UNION ALL SELECT 'Proposal Writing', d.id FROM departments d WHERE d.name = 'Business Development'
UNION ALL SELECT 'Market Research', d.id FROM departments d WHERE d.name = 'Business Development'
UNION ALL SELECT 'Product Strategy', d.id FROM departments d WHERE d.name = 'Business Development'
UNION ALL SELECT 'Solution Consulting', d.id FROM departments d WHERE d.name = 'Business Development'
UNION ALL SELECT 'Partnership Management', d.id FROM departments d WHERE d.name = 'Business Development'
UNION ALL SELECT 'Scientific Sales', d.id FROM departments d WHERE d.name = 'Business Development'

UNION ALL SELECT 'Strategic Planning', d.id FROM departments d WHERE d.name = 'Management'
UNION ALL SELECT 'Program Management', d.id FROM departments d WHERE d.name = 'Management'
UNION ALL SELECT 'OKR Management', d.id FROM departments d WHERE d.name = 'Management'
UNION ALL SELECT 'Budgeting', d.id FROM departments d WHERE d.name = 'Management'
UNION ALL SELECT 'Stakeholder Communication', d.id FROM departments d WHERE d.name = 'Management'
UNION ALL SELECT 'Decision Making', d.id FROM departments d WHERE d.name = 'Management'

UNION ALL SELECT 'Talent Acquisition', d.id FROM departments d WHERE d.name = 'HR & Admin'
UNION ALL SELECT 'HR Operations', d.id FROM departments d WHERE d.name = 'HR & Admin'
UNION ALL SELECT 'Payroll Management', d.id FROM departments d WHERE d.name = 'HR & Admin'
UNION ALL SELECT 'Employee Relations', d.id FROM departments d WHERE d.name = 'HR & Admin'
UNION ALL SELECT 'Performance Management', d.id FROM departments d WHERE d.name = 'HR & Admin'
UNION ALL SELECT 'HR Analytics', d.id FROM departments d WHERE d.name = 'HR & Admin'
UNION ALL SELECT 'Policy Compliance', d.id FROM departments d WHERE d.name = 'HR & Admin'

UNION ALL SELECT 'Financial Reporting', d.id FROM departments d WHERE d.name = 'Accounts and Finance'
UNION ALL SELECT 'Budgeting & Forecasting', d.id FROM departments d WHERE d.name = 'Accounts and Finance'
UNION ALL SELECT 'Cost Optimization', d.id FROM departments d WHERE d.name = 'Accounts and Finance'
UNION ALL SELECT 'Taxation', d.id FROM departments d WHERE d.name = 'Accounts and Finance'
UNION ALL SELECT 'Compliance & Auditing', d.id FROM departments d WHERE d.name = 'Accounts and Finance'
UNION ALL SELECT 'Revenue Accounting', d.id FROM departments d WHERE d.name = 'Accounts and Finance';
